CREATE DATABASE IF NOT EXISTS Spendee;
USE Spendee;

DROP TABLE IF EXISTS Movimenti;
DROP TABLE IF EXISTS Portafogli;
DROP TABLE IF EXISTS Categoria;


CREATE TABLE Portafogli
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Nome` VARCHAR(100) NOT NULL,
	PRIMARY KEY(`ID`)
) ENGINE = InnoDB;

CREATE TABLE Categorie
(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Nome` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB;

CREATE TABLE Movimenti
(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Descrizione` VARCHAR(100) NOT NULL,
    `Prezzo` FLOAT NOT NULL,
	`Data` DATE NOT NULL,
    `CategoriaID` INT NOT NULL,
	`PortafoglioID` INT NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`CategoriaID`) REFERENCES `Categorie` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (`PortafoglioID`) REFERENCES `Portafogli` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;
